name: Build and push image

on:
  push:
    branches: [ main ]
    tags: ["*"]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: kube-dind
    strategy:
      matrix:
        account:
          - '190367695196'
          - '352033354486'
          - '638663786504'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: configure aws
        uses: Blockdaemon/aws-configure-credentials@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: login to ecr
        uses: blockdaemon/ecr-login@v1
      - name: Build and push walletconnect
        uses: docker/build-push-action@v6
        env:
          CACHE_TO: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=190367695196.dkr.ecr.us-east-1.amazonaws.com/blockdaemon/evm-tracker:cache
        with:
          push: true
          tags: |
            190367695196.dkr.ecr.us-east-1.amazonaws.com/blockdaemon/evm-tracker:${{ github.ref_name }}
            352033354486.dkr.ecr.us-east-1.amazonaws.com/blockdaemon/evm-tracker:${{ github.ref_name }}
            638663786504.dkr.ecr.us-east-1.amazonaws.com/blockdaemon/evm-tracker:${{ github.ref_name }}
          cache-from: type=registry,type=registry,ref=190367695196.dkr.ecr.us-east-1.amazonaws.com/blockdaemon/evm-tracker:cache
          cache-to: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=190367695196.dkr.ecr.us-east-1.amazonaws.com/blockdaemon/evm-tracker:cache
